apiVersion: v1
kind: ConfigMap
metadata:
  name: task10-payment-config
data:
  DATABASE_HOST: postgres-payment
  DATABASE_USER: myuser
  DATABASE_DB: myapp

---
apiVersion: v1
kind: Secret
metadata:
  name: task10-payment-secret
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dk
  DATABASE_PASSWORD_WITH_NEW_LINE: cGFzc3dkCg==