apiVersion: batch/v1
kind: Job
metadata:
  name: task10-payment-initdb
spec:
  template:
    metadata:
      name: task10-payment-initdb
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: task10-payment-config
                  key: DATABASE_HOST
            - name: DATABASE_DB
              valueFrom:
                configMapKeyRef:
                  name: task10-payment-config
                  key: DATABASE_DB
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: task10-payment-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task10-payment-secret
                  key: DATABASE_PASSWORD
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $DATABASE_HOST;
                do echo waiting for database; sleep 2;
              done;
              psql postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST/$DATABASE_DB <<'EOF'
              create table invoice
              (
                  id       bigserial not null
                      constraint invoice_pk
                          primary key,
                  status   varchar(256),
                  pay_system_id bigint not null
              );
              EOF
  backoffLimit: 0
