apiVersion: apps/v1
kind: Deployment
metadata:
  name: task10-order-deployment
  labels:
    app: task10-order-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task10-order-app
  template:
    metadata:
      labels:
        app: task10-order-app
    spec:
      containers:
        - name: task10-order
          image: developmarat/task10.order:v1
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: task10-order-config
                  key: DATABASE_HOST
            - name: DATABASE_DB
              valueFrom:
                configMapKeyRef:
                  name: task10-order-config
                  key: DATABASE_DB
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: task10-order-config
                  key: DATABASE_USER
            - name: PAYMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: task10-order-config
                  key: PAYMENT_URL
            - name: STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: task10-order-config
                  key: STORE_URL
            - name: DELIVERY_URL
              valueFrom:
                configMapKeyRef:
                  name: task10-order-config
                  key: DELIVERY_URL
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task10-order-secret
                  key: DATABASE_PASSWORD
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 535
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 100