apiVersion: apps/v1
kind: Deployment
metadata:
  name: task10-store-deployment
  labels:
    app: task10-store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task10-store-app
  template:
    metadata:
      labels:
        app: task10-store-app
    spec:
      containers:
        - name: task10-store
          image: developmarat/task10.store:v1
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: task10-store-config
                  key: DATABASE_HOST
            - name: DATABASE_DB
              valueFrom:
                configMapKeyRef:
                  name: task10-store-config
                  key: DATABASE_DB
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: task10-store-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task10-store-secret
                  key: DATABASE_PASSWORD
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 535
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 100